import type { Copy } from './types.js';

/** Interface copy, BM first. Keys are screen.thing; the boards' own lines are kept word for word. */
export const COPY: Copy = {
  'brand.name': { bm: 'Ceritera', en: 'Ceritera' },
  'brand.line': { bm: 'Buku · Manusia · Dunia', en: 'Buku · Manusia · Dunia' },
  'brand.library': { bm: 'The Digital Library', en: 'The Digital Library' },

  'menu.continue': { bm: 'Teruskan', en: 'Continue' },
  'menu.new': { bm: 'Perjalanan Baru', en: 'New Journey' },
  'menu.settings': { bm: 'Tetapan', en: 'Settings' },
  'menu.credits': { bm: 'Penghargaan', en: 'Credits' },
  'menu.exit': { bm: 'Keluar', en: 'Exit' },
  'menu.quote': { bm: 'Setiap ilmu membuka jalan yang baru.', en: 'Every knowledge opens a new path.' },
  'menu.soon': { bm: 'Akan datang', en: 'Coming soon' },
  'menu.replace': { bm: 'Perjalanan baru akan menggantikan watak anda sekarang. Teruskan?', en: 'A new journey replaces your current character. Continue?' },

  'avatar.title': { bm: 'Pilih Avatar Anda', en: 'Choose Your Avatar' },
  'avatar.sub': { bm: 'Dunia yang sama. Cerita yang berbeza.', en: 'Same world. Different stories.' },
  'avatar.begin': { bm: 'Mula Perjalanan', en: 'Begin the Journey' },
  'avatar.back': { bm: 'Kembali', en: 'Back' },
  'avatar.stats': { bm: 'Sifat', en: 'Attributes' },
  'avatar.perk': { bm: 'Kelebihan', en: 'Strength' },
  'avatar.look': { bm: 'Pakaian', en: 'Attire' },
  'avatar.draft': { bm: 'Draf', en: 'Draft' },
  'avatar.keys': { bm: '← → pilih · Enter mula · Esc kembali', en: '← → choose · Enter begin · Esc back' },

  'char.title': { bm: 'Watak', en: 'Character' },
  'char.overview': { bm: 'Ringkasan', en: 'Overview' },
  'char.equipment': { bm: 'Peralatan', en: 'Equipment' },
  'char.skills': { bm: 'Kemahiran', en: 'Skills' },
  'char.appearance': { bm: 'Rupa', en: 'Appearance' },
  'char.level': { bm: 'Tahap', en: 'Level' },
  'char.quote': { bm: 'Setiap perjalanan adalah sebuah pelajaran.', en: 'Every journey is a lesson.' },
  'char.enter': { bm: 'Masuk ke Dewan Ilmu', en: 'Enter Dewan Ilmu' },
  'char.menu': { bm: 'Menu utama', en: 'Main menu' },
  'char.empty': { bm: 'Kosong', en: 'Empty' },
  'char.loading': { bm: 'Memuatkan model 3D…', en: 'Loading the 3D model…' },

  'world.building': { bm: 'Dewan Ilmu sedang dibina.', en: 'Dewan Ilmu is being built.' },
  'world.building.sub': { bm: 'Dewan ini ialah hirisan menegak M1: Nanite, Lumen, MegaLights dan rak yang diisi dari katalog. Buat masa ini, papan konsep menandakan tempatnya.', en: 'The hall is the M1 vertical slice: Nanite, Lumen, MegaLights and shelves filled from the catalogue. For now the concept board holds its place.' },
  'world.back': { bm: 'Kembali ke watak', en: 'Back to character' },

  'hud.health': { bm: 'Nyawa', en: 'Health' },
  'hud.stamina': { bm: 'Tenaga', en: 'Stamina' },
  'hud.spirit': { bm: 'Semangat', en: 'Spirit' },
  'hud.ilham': { bm: 'Ilham', en: 'Ilham' },
  'hud.ultimate': { bm: 'Muktamad', en: 'Ultimate' },
  'hud.loading': { bm: 'Memuatkan Dewan Ilmu…', en: 'Loading Dewan Ilmu…' },
  'hud.click': { bm: 'Klik untuk melihat sekeliling', en: 'Click to look around' },
  'hud.paused': { bm: 'Jeda', en: 'Paused' },
  'hud.resume': { bm: 'Sambung', en: 'Resume' },
  'hud.character': { bm: 'Lembaran watak', en: 'Character sheet' },
  'hud.menu': { bm: 'Menu utama', en: 'Main menu' },
  'hud.keys': { bm: 'Kekunci', en: 'Keys' },
  'hud.layout.arrows': { bm: 'Anak panah + Q W E R', en: 'Arrows + Q W E R' },
  'hud.layout.wasd': { bm: 'WASD + 1 2 3 4', en: 'WASD + 1 2 3 4' },
  'hud.sound': { bm: 'Bunyi', en: 'Sound' },
  'hud.on': { bm: 'Hidup', en: 'On' },
  'hud.off': { bm: 'Mati', en: 'Off' },
  'hud.dead': { bm: 'Kau tumbang.', en: 'You have fallen.' },
  'hud.respawn': { bm: 'Bangun semula dalam', en: 'Back on your feet in' },
  'hud.levelup': { bm: 'Tahap naik', en: 'Level up' },
  'hud.kills': { bm: 'Bayang tumpas', en: 'Shadows felled' },
  'hud.combo': { bm: 'rentetan', en: 'combo' },
  'hud.lock': { bm: 'Sasaran', en: 'Target' },
  'hud.dodged': { bm: 'elak', en: 'dodged' },
  'hud.attack': { bm: 'Serang', en: 'Strike' },
  'hud.jump': { bm: 'Lompat', en: 'Jump' },
  'hud.dodge': { bm: 'Elak', en: 'Dodge' },
  'hud.slam': { bm: 'Hentak', en: 'Slam' },
  'hud.sprint': { bm: 'Pecut', en: 'Sprint' },
  'hud.controls': { bm: 'Gerak ← ↑ ↓ →  ·  Tengok: tetikus\nPecut Shift  ·  Lompat Space (dua kali di udara)\nElak C / klik kanan  ·  Serang F / klik kiri\nHentak V di udara  ·  Kunci sasaran Tab\nKemahiran Q W E R  ·  Jeda Esc', en: 'Move ← ↑ ↓ →  ·  Look: mouse\nSprint Shift  ·  Jump Space (twice in the air)\nDodge C / right click  ·  Strike F / left click\nSlam V in the air  ·  Lock target Tab\nSkills Q W E R  ·  Pause Esc' },
  'hud.controls.wasd': { bm: 'Gerak W A S D  ·  Tengok: tetikus\nPecut Shift  ·  Lompat Space (dua kali di udara)\nElak C / klik kanan  ·  Serang F / klik kiri\nHentak V di udara  ·  Kunci sasaran Tab\nKemahiran 1 2 3 4  ·  Jeda Esc', en: 'Move W A S D  ·  Look: mouse\nSprint Shift  ·  Jump Space (twice in the air)\nDodge C / right click  ·  Strike F / left click\nSlam V in the air  ·  Lock target Tab\nSkills 1 2 3 4  ·  Pause Esc' },
  'char.kit': { bm: 'Kemahiran', en: 'Skills' },
  'char.cooldown': { bm: 'tunggu', en: 'cooldown' },
  'error.offline': { bm: 'Tiada sambungan. Cuba sebentar lagi.', en: 'No connection. Try again in a moment.' },
  'lang.switch': { bm: 'English', en: 'Bahasa Melayu' },
};
