// Postgres adapter (Supabase): what the game runs on when it is deployed to Vercel. The queries are written once, in the
// SQLite dialect the rest of the code uses — `?` placeholders, INTEGER columns — and this adapter bridges the gap:
// `?` becomes `$n`, and 64-bit / numeric results come back as JS numbers like they do from SQLite.
import postgres from 'postgres';
import type { Db, Param, Stmt } from './types.js';
import { SCHEMA } from './schema.js';

/** `?` → `$1, $2, …`, leaving quoted strings and identifiers alone. */
export function numberParams(sql: string): string {
  let out = '', n = 0, quote = '';
  for (const ch of sql) {
    if (quote) { if (ch === quote) quote = ''; out += ch; }
    else if (ch === "'" || ch === '"') { quote = ch; out += ch; }
    else out += ch === '?' ? `$${++n}` : ch;
  }
  return out;
}

/**
 * The SQLite schema, in Postgres types. Timestamps are milliseconds, past int4, so every INTEGER becomes BIGINT;
 * AUTOINCREMENT keys become identity columns. One source of truth: new tables are only ever added to SCHEMA.
 */
export const PG_SCHEMA = SCHEMA
  .replace(/INTEGER PRIMARY KEY AUTOINCREMENT/g, 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
  .replace(/\bINTEGER\b/g, 'BIGINT')
  .replace(/\bREAL\b/g, 'DOUBLE PRECISION') + `
-- Supabase serves the public schema over its REST API to anyone holding the (public) anon key. The game never uses that
-- API — it connects as the tables' owner, which row level security does not apply to — so every table gets RLS with no
-- policies: closed to the API, untouched for the game. Only tables still without it, so cold starts take no locks.
DO $$ DECLARE t text; BEGIN
  FOR t IN SELECT c.relname FROM pg_class c WHERE c.relnamespace = current_schema()::regnamespace AND c.relkind = 'r' AND NOT c.relrowsecurity LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
  END LOOP;
END $$;
`;

const toNumber = (x: string) => Number(x);

export interface PgOptions {
  /** Schema to work in (tests give each database its own). Defaults to the server's search_path, i.e. public. */
  schema?: string;
  max?: number;
}

export function openPostgres(url: string, o: PgOptions = {}): Db & { migrate(): Promise<void>; close(): Promise<void> } {
  const sql = postgres(url, {
    prepare: false, // required behind Supabase's transaction pooler (port 6543)
    max: o.max ?? 5,
    idle_timeout: 20,
    onnotice: () => {}, // "relation already exists, skipping" on every migrate
    connection: o.schema ? { search_path: o.schema } : {},
    // COUNT(*) is int8 and SUM() is numeric; the game expects numbers, as SQLite gives it.
    types: {
      int8: { to: 20, from: [20], serialize: String, parse: toNumber },
      numeric: { to: 1700, from: [1700], serialize: String, parse: toNumber },
    },
  });
  const rows = <T,>(q: postgres.Sql | postgres.TransactionSql, text: string, params: Param[]) =>
    q.unsafe(numberParams(text), params as postgres.ParameterOrJSON<never>[]) as unknown as Promise<T[]>;

  return {
    async get<T>(text: string, params: Param[] = []) { return (await rows<T>(sql, text, params))[0]; },
    all: <T,>(text: string, params: Param[] = []) => rows<T>(sql, text, params),
    async run(text: string, params: Param[] = []) { await rows(sql, text, params); },
    /** One transaction: all statements commit together or not at all. */
    async batch(stmts: Stmt[]) {
      if (!stmts.length) return;
      await sql.begin(async (tx) => { for (const [text, params] of stmts) await rows(tx, text, params); });
    },
    /** Idempotent. Serialised with an advisory lock so cold starts racing each other cannot trip over CREATE IF NOT EXISTS. */
    async migrate() {
      if (o.schema) await sql.unsafe(`CREATE SCHEMA IF NOT EXISTS "${o.schema}"`);
      await sql.begin(async (tx) => { await tx.unsafe('SELECT pg_advisory_xact_lock(20260921)'); await tx.unsafe(PG_SCHEMA).simple(); });
    },
    close: () => sql.end({ timeout: 1 }),
  };
}
